# Generated by Django 4.1.5 on 2023-01-19 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='embeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_id', models.CharField(max_length=50, verbose_name='模型ID')),
                ('embedding_name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('embedding_creator', models.CharField(max_length=50, verbose_name='创建者')),
                ('embedding_status', models.BooleanField(default=False, verbose_name='完成状态')),
                ('embedding_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Embedding模型信息',
                'verbose_name_plural': 'Embedding模型信息管理',
            },
        ),
    ]
