# Generated by Django 4.1.5 on 2023-01-19 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiDream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_id', models.CharField(max_length=50, verbose_name='生图ID')),
                ('generate_Tag', models.JSONField(verbose_name='Tag列表')),
                ('generate_creator', models.CharField(max_length=50, verbose_name='创建者')),
                ('generate_status', models.BooleanField(default=False, verbose_name='完成状态')),
                ('generate_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生图信息',
                'verbose_name_plural': '生图信息管理',
            },
        ),
        migrations.AlterModelOptions(
            name='embeddinginfo',
            options={'verbose_name': 'Tag模型信息', 'verbose_name_plural': 'Tag模型信息管理'},
        ),
    ]
